issuer: http://127.0.0.1:5556/dex

storage:
  type: memory
  config:
    file: examples/dex.db

web:
  allowedOrigins: ['*']
  http: 0.0.0.0:5556

telemetry:
  http: 0.0.0.0:5558
  # enableProfiling: true

# Default values shown below
oauth2:
  # grantTypes determines the allowed set of authorization flows.
  grantTypes:
    - 'authorization_code'
    - 'refresh_token'
    - 'implicit'
    - 'password'
    - 'urn:ietf:params:oauth:grant-type:device_code'
    - 'urn:ietf:params:oauth:grant-type:token-exchange'

staticClients:
  - id: example-app
    redirectURIs:
      - https://oauth.pstmn.io/v1/callback
      - http://localhost:4200/callback
    name: 'Example App'
    public: true

connectors:
  - type: mockCallback
    id: mock
    name: Example
enablePasswordDB: true

staticPasswords:
  - email: 'admin@example.com'
    # bcrypt hash of the string "password": $(echo password | htpasswd -BinC 10 admin | cut -d: -f2)
    hash: '$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W'
    username: 'admin'
    userID: '08a8684b-db88-4b73-90a9-3cd1661f5466'
